#version 460
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types : require

layout(local_size_x = 64) in;

layout(set = 0, binding = 0) buffer Data {
    f16vec4 data[];
} InOutBuffer;

#define APPLY4(OP, i)  OP(i) OP((i)+1) OP((i)+2) OP((i)+3)
#define APPLY15(OP)    APPLY4(OP, 1) APPLY4(OP, 5) APPLY4(OP, 9) \
                       OP(13) OP(14) OP(15)
#define APPLY16(OP)    OP(0) APPLY15(OP)

#define INIT(i) a[(i)] = f16vec4(       \
    0.1 * float(4 * (i) - 3),           \
    0.1 * float(4 * (i) - 2),           \
    0.1 * float(4 * (i) - 1),           \
    0.1 * float(4 * (i))                \
);

#define STEP(i) a[(i)] = fma(a[(i)], m, a[((i) + 1) & 15]);

void main() {
    uint index = gl_GlobalInvocationID.x;

    f16vec4 a[16];
    a[0] = InOutBuffer.data[index % 1024u];
    APPLY15(INIT)

    f16vec4 m = f16vec4(float16_t(1.0009765625));

    for (int iteration = 0; iteration < 65536; ++iteration) {
        APPLY16(STEP)
    }

    InOutBuffer.data[index] =
        ((a[0]  + a[1])  + (a[2]  + a[3]))  +
        ((a[4]  + a[5])  + (a[6]  + a[7]))  +
        ((a[8]  + a[9])  + (a[10] + a[11])) +
        ((a[12] + a[13]) + (a[14] + a[15]));
}
