#version 450

layout(local_size_x = 1) in;

layout(set = 0, binding = 0) buffer Data {
    uint data[];
} Buffer;

layout(push_constant) uniform PushConstants {
    uint mask; // Kept for host compatibility
} pushConstants;

void main() {
    uint index = 0;
    
    // Raw chasing without mask
    for (uint i = 0; i < 1000000; i++) {
        index = Buffer.data[index];
    }

    if (index == 0xDEADBEEF) {
        Buffer.data[0] = index;
    }
}
