#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Data {
    uint data[];
} Buffer;

layout(push_constant) uniform PushConstants {
    uint iterations;
    uint startIndex;
} pc;

void main() {
    uint index = pc.startIndex;
    uint iters = pc.iterations;
    
    // Serial pointer chasing loop across 128-byte cache lines
    for (uint i = 0; i < iters; i++) {
        index = Buffer.data[index];
    }

    if (index == 0xDEADBEEF) {
        Buffer.data[0] = index;
    }
}
