#version 460

#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer OutputBuffer {
    double data[];
} outBuffer;

void main() {
    uint index = gl_GlobalInvocationID.x;
    double val = 1.0;
    double add = double(index) * 0.00000001;
    for (int i = 0; i < 65536; ++i) {
        val = fma(val, 1.000001 + add, 1.0);
    }
    outBuffer.data[index] = val;
}
